
jenkins:
    systemMessage: "Amazon Fargate Demo"
    numExecutors: 0
    # remotingSecurity:
    #   enabled: true
    # agentProtocols:
    #     - "JNLP4-connect"
    securityRealm:
      local:
        allowsSignup: false
        users:
          - id: ecsuser
            # password: \$${ADMIN_PWD}
            password: password
    authorizationStrategy:
      unsecured
      # loggedInUsersCanDoAnything
      # globalMatrix:
      #   grantedPermissions:
      #     - "Overall/Read:authenticated"
      #     - "Job/Read:authenticated"
      #     - "View/Read:authenticated"
      #     - "Overall/Administer:authenticated"
    # crumbIssuer: "standard"
    # slaveAgentPort: 50000
    # clouds:
    #     # - ecs:
    #     #       allowedOverrides: "inheritFrom,label,memory,cpu,image"
    #     #       credentialsId: ""
    #     #       cluster: arn:aws:ecs:eu-west-1:626964907981:cluster/jenkins-agent-ecs-cluster-staging
    #     #       name: "fargate-cloud-spot"
    #     #       regionName: ${cluster_region}
    #     #       retentionTimeout: 10
    #     #       jenkinsUrl: "http://${jenkins_cloud_map_name}:8080"
    #     #       templates:
    #     #           - cpu: "512"
    #     #             image: "jenkins/inbound-agent"
    #     #             label: "build-example-spot"
    #     #             executionRole: arn:aws:iam::626964907981:role/jenkins-role-staging
    #     #             launchType: "FARGATE"
    #     #             memory: 0
    #     #             memoryReservation: 1024
    #     #             networkMode: "awsvpc"
    #     #             privileged: false
    #     #             remoteFSRoot: "/home/jenkins"
    #     #             securityGroups: ${agent_security_groups}
    #                     # - sg-01301b4c93f112ab2
    #     #             sharedMemorySize: 0
    #     #             subnets: ${subnets}
    #     #             templateName: "build-example"
    #     #             uniqueRemoteFSRoot: false
    #   - ecs:
    #       allowedOverrides: "inheritFrom,label,memory,cpu,image"
    #       credentialsId: ""
    #       cluster: arn:aws:ecs:eu-west-1:626964907981:cluster/jenkins-agent-ecs-cluster-staging
    #       name: "fargate-cloud"
    #       regionName: eu-west-1
    #       retentionTimeout: 10
    #       jenkinsUrl: "http://${jenkins_cloud_map_name}:8080"
    #       templates:
    #         - cpu: "512"
    #           image: "jenkins/inbound-agent"
    #           label: "build-example"
    #           executionRole: arn:aws:iam::626964907981:role/jenkins-role-staging
    #           launchType: "FARGATE"
    #           memory: 0
    #           memoryReservation: 1024
    #           networkMode: "awsvpc"
    #           privileged: false
    #           remoteFSRoot: "/home/jenkins"
    #           securityGroups:
    #             - sg-01301b4c93f112ab2
    #           sharedMemorySize: 0
    #           subnets:
    #             - subnet-0c488e70f54d09920
    #             - subnet-0441deed830e959fb
    #           templateName: "build-example"
    #           uniqueRemoteFSRoot: false

security:
  sSHD:
    port: -1

jobs:
  - script: >
      pipelineJob('Simple job critical task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent {
                      ecs {
                          inheritFrom 'build-example'
                      }
                  }
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on non spot instance"
                            }
                            sh 'sleep 120'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
  - script: >
      pipelineJob('Simple job non critical task') {
        definition {
          cps {
            script('''
              pipeline {
                  agent {
                      ecs {
                          inheritFrom 'build-example-spot'
                      }
                  }
                  stages {
                    stage('Test') {
                        steps {
                            script {
                                sh "echo this was executed on a spot instance"
                            }
                            sh 'sleep 120'
                            sh 'echo sleep is done'
                        }
                    }
                  }
              }'''.stripIndent())
              sandbox()
          }
        }
      }
